DROP TABLE categoria CASCADE CONSTRAINTS;

DROP TABLE cliente CASCADE CONSTRAINTS;

DROP TABLE detalhes_pedido CASCADE CONSTRAINTS;

DROP TABLE entrega CASCADE CONSTRAINTS;

DROP TABLE fornecedor CASCADE CONSTRAINTS;

DROP TABLE ingrediente CASCADE CONSTRAINTS;

DROP TABLE lanche CASCADE CONSTRAINTS;

DROP TABLE pagamento CASCADE CONSTRAINTS;

DROP TABLE pedido CASCADE CONSTRAINTS;

DROP TABLE possui CASCADE CONSTRAINTS;

DROP TABLE vende CASCADE CONSTRAINTS;

DROP SEQUENCE s_cliente;

DROP SEQUENCE s_detalhes_pedido;
DROP SEQUENCE s_entrega;
DROP SEQUENCE s_pagamento;
DROP SEQUENCE s_pedido;

DROP SEQUENCE s_fornecedor;
DROP SEQUENCE s_ingrediente;
DROP SEQUENCE s_categoria;
DROP SEQUENCE s_lanche;